server:
  port: ${CUSTOM.SERVER.PORT:9011}

### Mongo database configuration
spring:
  data:
    mongodb:
      uri: ${MONGODB.URL.CONNECTION:mongodb://mitocode:mitocode@localhost:27018/mitocode?authSource=admin}

kafka:
  mitocode:
    topic: mitocode
    server: 127.0.0.1
    port: 9092