server:
  port: ${CUSTOM.SERVER.PORT:9005}

# Circuit Breaker configuration
# resilience4j:
#   circuitbreaker:
#     configs:
#       userServiceCircuitBreaker: # cualquierId
#         slidingWindowSize: 8
#         failureRateThreshold: 60
#         waitDurationInOpenState: 20s
#         permittedNumberOfCallsInHalfOpenState: 8
#         slowCallDurationThreshold: 1s
#         slowCallRateThreshold: 50
        
#       productServiceCircuitBreaker:
#         slidingWindowSize: 8
#         failureRateThreshold: 60
#         waitDurationInOpenState: 20s
#         permittedNumberOfCallsInHalfOpenState: 4
#         slowCallDurationThreshold: 1s
#         slowCallRateThreshold: 50

#     instances:
#       user-service-cb:
#         base-config: userServiceCircuitBreaker #cualquierId
#       product-service-cb:
#         base-config: productServiceCircuitBreaker
spring:
  main:
    web-application-type: reactive

info:
  app:
    name: Client Service Webflux Mitocode
    description: Módulo de la arquitectura de Microservicios
    version: 0.0.1


# Actuator configuration
management:
  endpoints:
    info:
      env:
        enabled: true
    web:
      exposure:
        # include: 'metrics, disk_space, mem, cpu, prometheus'
        include: '*'
        base-path: /actuator
    tracing:
      sampling:
        probability: 1.0

# Logging Configuration
logging:
  level:
    org:
      springframework:
        web: ALL
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
