server:
  port: ${CUSTOM.SERVER.PORT:9080}

# Eureka Client Config
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}

# Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    configs:
      circuitBreakerProduct:
        slidingWindowSize: 16
        failureRateThreshold: 75
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 200ms
        slowCallRateThreshold: 50
    instances:
      product-cb:
        base-config: circuitBreakerProduct
  timelimiter:
    configs:
      timelimiterProduct:
        timeoutDuration: 150ms
    instances:
      product-cb:
        base-config: timelimiterProduct

# Cloud Gateway Routes
spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: product-cb
                statusCodes: 400, 401, 403, 500, 503, 504
                fallbackUri: forward:/api/user-service/mitocode/user


            # - AddRequestHeader=appCallerName, ${filter.parameters.appCallerName}
            # - AddRequestParameter=flag, ${filter.parameters.flag}
            # - name: MitocodeProductFilter
            #   args:
            #     headerKey: appCallerName
            #     headerValue: Java17

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2

        - id: user-service-fallback
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/mitocode/user
          filters:
            - StripPrefix=4

mitocode:
  security:
    client: mitocode
    secret: mitocode
    key: RHDGOCvGNcGvpNnUMR2EEgQvCqfXE7pOQDNm1vHIdqmtBgPAtyt7E/03rPj6dtGERMrtdlivexlIX+x6hIycJgQGgmEAnBHRgRTVOC0iLzKq7F/OGcwWrSe2Jf3gO11E187v37gaAt/2wdr22uf+SsjjLYnUNGpu85NkL3eEgUwJEsyPkXzFSG42+QP3eR7cW40FGI3qyS5BLO8UPg/OxOg5ykezsapj0lwIDAQABAoIBAC2nQn28/eCPnDQWon0jG046cEFR46M446Szjz8PX5V6IB+R3Is3QDm749DWRzAHLUAeRd+Ffhpr2T4Z/jEIAw3affzmqZOR8CINUj0PauAnU/Xv/xIzeJ6Ugjx4DrDcaONDSOGgVyiVQewJ2Pn4q1mJf0HRW7t4fszMdzKmue9td6vAet7s//5XDFFFnvkHxZ/XSvBHfM+cWRlAkB89UnzAk5thdWTM+9LdDZhxnGQe0XwvxXmURb+rezGIrfV+6POSobF6m7kwiW0xz+ynxCQ0i0PAlyM7F2mC38HpTw+Kxo2bmrnWjpd0AakTSqTA8+/RGgLZXLviLPALM5s8ypECgYEA3BvLmlwLZE9cvzmavdWfXi+IQt7vzOTK+uA6twk/7hOKg1QvFaEz
#    key: mitocode