server:
  port: ${CUSTOM.SERVER.PORT:9999}

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}

### Mongo database configuration
spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: mitocodedb
      uri: ${MONGODB.URL.CONNECTION:mongodb://mitocode:mitocode@localhost:27018}
      authentication-database: admin
      
# Actuator configuration
info:
  app:
    name: Product Service Microservice
    description: Módulo de la arquitectura que disponibiliza información de los productos
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: swagger-ui.html
    enabled: true
  show-actuator: false

logging:
  level:
    org:
      springframework:
        web: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'