server:
  port: ${CUSTOM.SERVER.PORT:9002}

  # security:
  #   oauth2:
  #     client:
  #       provider:
  #         external:
  #           issuer-uri: http://localhost:8080/realms/external
  #       registration:
  #         external:
  #           provider: external
  #           client-name: external-client
  #           client-id: external-client
  #           client-secret: MtbhMWVBcUi7Xp31U6GEofDp7jS88B6X
  #           scope: openid
  #           authorization-grant-type: authorization_code

### Mongo database configuration
spring:
  data:
    mongodb:
      uri: ${MONGODB.URL.CONNECTION:mongodb://mitocode:mitocode@localhost:27017/mitocode?authSource=admin}


info:
  app:
    name: Producto Service Mitocode
    description: Módulo de la arquitectura de Microservicios que disponibiliza la información de los productos
    version: 0.0.1

kafka:
  mitocode:
    topic: mitocode
    server: 127.0.0.1
    port: 9092