server:
  port: ${CUSTOM.SERVER.PORT:9001}

# Eureka Client Configuration
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${CUSTOM.EUREKA.HOST:http://localhost:8761/eureka}

# MongoDB database configuration
spring:
  data:
    mongodb:
      uri: mongodb://mitocode:mitocode@localhost:27017/mitocode?authSource=admin